# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='username',
        ),
    ]
